apiVersion: apps/v1
kind: Deployment
metadata:
  name: bag-api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bag-api-v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: bag-api-v1
    spec:
      containers:
      - name: bag-api-v1
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
