apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bag-api
  annotations:
    kubernetes.io/ingress.global-static-ip-name: crypto-bag-api
    networking.gke.io/managed-certificates: bag
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: "api.cryptobag.podnov.com"
    http:
      paths:
      - pathType: Prefix
        path: "/bag/api/v1/*"
        backend:
          serviceName: bag-api-v1
          servicePort: 80

