apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bag-ui
  annotations:
    kubernetes.io/ingress.global-static-ip-name: crypto-bag
    networking.gke.io/managed-certificates: bag
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: "cryptobag.podnov.com"
    http:
      paths:
      - pathType: Prefix
        path: "/*"
        backend:
          service:
            name: bag-ui-v1
            port:
              number: 80

